const QuestionActionTypes = {
    FETCH_QUESTIONS: 'FETCH_QUESTIONS',
    FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
    FETCH_QUESTIONS_FAILURE: 'FETCH_QUESTIONS_FAILURE'
}

export default QuestionActionTypes;