const UserAnswerActions = {
    SELECT_USER_ANSWER: 'SELECT_USER_ANSWER',
    SUBMIT_USER_ANSWER_START: 'SUBMIT_USER_ANSWER_START',
    SUBMIT_USER_ANSWER_SUCCESS: 'SUBMIT_USER_ANSWER_SUCCESS',
    SUBMIT_USER_ANSWER_FAILURE: 'SUBMIT_USER_ANSWER_FAILURE',
    CLEAR_USER_ANSWERS: 'CLEAR_USER_ANSWER',
    CLEAR_ATTEMPT_RESULT: 'CLEAR_ATTEMPT_RESULT'
}

export default UserAnswerActions;